name: up42
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - affine=2.3.0=py_0
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.3.2=py38h578d9bd_0
  - argcomplete=1.12.3=pyhd8ed1ab_2
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - astroid=2.8.0=py38h578d9bd_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - autopep8=1.5.7=pyhd8ed1ab_0
  - awscli=1.20.54=py38h578d9bd_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=21.9b0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - boost-cpp=1.74.0=h312852a_4
  - boto=2.49.0=py_0
  - boto3=1.18.54=pyhd8ed1ab_0
  - botocore=1.21.54=pyhd8ed1ab_0
  - branca=0.4.2=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.6=py38h3931269_1
  - cfitsio=3.470=hb418390_7
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - ciso8601=2.2.0=py38h497a2fe_0
  - click=7.1.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_0
  - colorama=0.4.3=py_0
  - coverage=5.5=py38h497a2fe_0
  - coverage-badge=1.0.1=pyh9f0ad1d_0
  - crcmod=1.7=py38h497a2fe_1006
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.79.1=h2574ce0_1
  - cycler=0.10.0=py_2
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.15.2=py38h578d9bd_2
  - entrypoints=0.3=pyhd8ed1ab_1003
  - executing=0.8.1=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - fasteners=0.16=pyhd8ed1ab_0
  - fiona=1.8.20=py38hbb147eb_1
  - folium=0.12.0=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=hba837de_1005
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.10.4=h0708190_1
  - freexl=1.0.6=h7f98852_0
  - gcs-oauth2-boto-plugin=3.0=pyhd8ed1ab_0
  - gdal=3.3.2=py38h81a01a0_3
  - geojson=2.5.0=py_0
  - geomet=0.3.0=pyhd3deb0d_0
  - geopandas=0.9.0=pyhd8ed1ab_1
  - geopandas-base=0.9.0=pyhd8ed1ab_1
  - geos=3.9.1=h9c3ff4c_2
  - geotiff=1.7.0=h08e826d_2
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - google-apitools=0.5.32=pyhd8ed1ab_0
  - google-reauth=0.1.1=pyhd3deb0d_0
  - gst-plugins-base=1.18.5=hf529b03_0
  - gstreamer=1.18.5=h76c114f_0
  - gsutil=5.2=pyhd8ed1ab_0
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_100
  - html2text=2020.1.16=py_0
  - httplib2=0.19.1=pyhd8ed1ab_0
  - icecream=2.1.1=pyhd8ed1ab_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - importlib_metadata=4.8.1=hd8ed1ab_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.4.1=py38he5a9106_0
  - ipython=7.28.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - isort=5.9.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json-c=0.15=h98cffda_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.0.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py38h578d9bd_0
  - jupyter_server=1.11.1=pyhd8ed1ab_0
  - jupyterlab=3.1.17=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kealib=1.4.14=h87e4c3c_3
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.19.2=hcc1bbae_2
  - lazy-object-proxy=1.6.0=py38h497a2fe_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.79.1=h2574ce0_1
  - libdap4=3.20.6=hd7c4107_2
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.4.2=h9c3ff4c_4
  - libgcc-ng=11.2.0=h1d223b6_9
  - libgdal=3.3.2=h6acdded_3
  - libgfortran-ng=11.2.0=h69a702a_9
  - libgfortran5=11.2.0=h5c6108e_9
  - libglib=2.68.4=h174f98d_1
  - libgomp=11.2.0=h1d223b6_9
  - libiconv=1.16=h516909a_0
  - libkml=1.3.0=h238a007_1014
  - liblapack=3.9.0=11_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - librttopo=1.1.0=h1185371_6
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libspatialite=5.0.1=h5cf074c_8
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_9
  - libtiff=4.3.0=hf544144_1
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h497a2fe_0
  - matplotlib=3.4.3=py38h578d9bd_1
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mistune=0.8.4=py38h497a2fe_1004
  - mock=2.0.0=pyhd8ed1ab_1003
  - monotonic=1.5=py_0
  - more-itertools=8.10.0=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - mypy=0.910=py38h497a2fe_0
  - mypy_extensions=0.4.3=py38h578d9bd_3
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbclassic=0.3.2=pyhd8ed1ab_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.2.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.4=pyha770c72_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numpy=1.21.2=py38he2449b9_0
  - oauth2client=4.1.3=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py38h43a58ef_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pbr=5.6.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py38h8e6f84c_0
  - pip=21.2.4=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - pluggy=1.0.0=py38h578d9bd_1
  - poppler=21.09.0=ha39eefc_3
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=13.3=h2510834_0
  - proj=8.1.0=h277dcde_1
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py=1.10.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.7.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pylint=2.11.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyproj=3.2.1=py38h3701b11_1
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - pytest=6.2.5=py38h578d9bd_0
  - pytest-cov=2.12.1=pyhd8ed1ab_0
  - pytest-mypy=0.8.0=pyhd8ed1ab_0
  - pytest-pylint=0.18.0=pyhd3deb0d_0
  - pytest-runner=5.3.1=pyhd8ed1ab_0
  - python=3.8.12=hb7a2778_0_cpython
  - python-dateutil=2.7.5=py_0
  - python-dotenv=0.19.0=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_1
  - pyzmq=22.3.0=py38h2035c66_0
  - qt=5.12.9=hda022c4_4
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.11.2=pyhd8ed1ab_0
  - rasterio=1.2.9=py38hbb95bec_0
  - readline=8.1=h46c0cb4_0
  - regex=2021.9.24=py38h497a2fe_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-mock=1.9.3=pyhd8ed1ab_0
  - requests-unixsocket=0.2.0=py_0
  - retry_decorator=1.1.1=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - rtree=0.9.7=py38h02d302b_2
  - s3transfer=0.5.0=pyhd8ed1ab_0
  - sat-search=0.3.0=py_0
  - sat-stac=0.4.1=pyh44b312d_0
  - scikit-learn=1.0=py38hacb3eff_1
  - scipy=1.7.1=py38h56a6a73_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentinelsat=1.1.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h578d9bd_2
  - shapely=1.7.1=py38hb7fe4a8_5
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.2.0=py38h578d9bd_1
  - snuggs=1.4.7=py_0
  - socksipy-branch=1.01=pyh9f0ad1d_0
  - sqlite=3.36.0=h9cd32fc_2
  - statsmodels=0.13.0=py38h6c62de6_0
  - terminado=0.12.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.2.0=pyh8a188c0_0
  - tiledb=2.3.4=he87e0bf_0
  - tk=8.6.11=h27826a3_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=1.2.1=pyhd8ed1ab_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typed-ast=1.4.3=py38h497a2fe_0
  - typing-extensions=3.10.0.2=hd8ed1ab_0
  - typing_extensions=3.10.0.2=pyha770c72_0
  - tzcode=2021a=h7f98852_2
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py38h578d9bd_4
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - wrapt=1.12.1=py38h497a2fe_3
  - xerces-c=3.2.3=h9d8b166_2
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - area==1.1.1
    - fake-geo-images==0.1.1
    - filelock==3.1.0
    - imageio==2.9.0
    - morecantile==2.1.4
    - networkx==2.6.3
    - pydantic==1.8.2
    - pywavelets==1.1.1
    - rio-cogeo==2.3.1
    - scikit-image==0.18.3
    - tifffile==2021.8.30
    - up42-blockutils==1.0.2
prefix: /home/jonathan/anaconda3/envs/up42
